### ISSUE TITLE
登录报错

### ISSUE THREAD

**Issue by Stripyuan** [pig6/wxrobot#14]
Downloading QR code.
██████████████████████████████████████████████████████████████████████████████
██              ████  ████████  ██████████████████  ██  ██████              ██
██  ██████████  ████  ██  ████  ██████████  ████████  ████████  ██████████  ██
██  ██      ██  ██      ████        ██    ██    ████  ██    ██  ██      ██  ██
██  ██      ██  ██  ██  ██  ████  ██  ████  ████████        ██  ██      ██  ██
██  ██      ██  ████  ██  ████  ██  ██      ██    ██    ██████  ██      ██  ██
██  ██████████  ██████      ████  ██  ████  ██    ████  ██████  ██████████  ██
██              ██  ██  ██  ██  ██  ██  ██  ██  ██  ██  ██  ██              ██
████████████████████  ██    ████    ████  ██  ████    ██    ██████████████████
████████    ██    ██      ████████  ████████  ██  ██████████████████    ██████
████  ██  ██  ██      ████████████████████      ██    ██            ██    ████
████      ████  ██  ██      ██  ██      ████    ██    ██            ██████  ██
████  ██████  ██  ██  ██  ██  ██████████  ██  ████████  ██      ████    ██  ██
██  ██  ██                ██████    ██      ████  ██████    ██    ██  ██    ██
██████    ██████              ████  ██      ██      ██        ████  ██  ██████
██████████  ██    ████    ████  ██████████    ██      ██  ██    ██          ██
██  ████████  ████      ██  ████    ██████  ██  ████████  ██  ████        ████
████████              ██████    ████    ████      ██  ████  ██    ████  ██  ██
██        ████████    ██  ██      ████  ████████      ██  ██  ██  ██████  ████
██      ██  ██  ████  ██          ██        ██████  ████  ██████  ████  ██  ██
██  ████  ████████    ██  ██      ██    ██████  ██    ██████  ██████  ████████
████████  ██      ██    ████████    ████  ██  ██    ██  ██      ██    ████████
██  ████████████  ██    ██  ████    ████        ██    ██    ████    ██    ████
██      ██  ██  ████  ████  ██    ████████████████  ████  ████  ██  ██████  ██
████          ██      ████████      ██████  ██      ██        ██  ████  ██████
████      ██      ██████    ██████  ██      ██  ████    ██  ██  ████  ██  ████
██  ██      ██████  ██    ██████████████      ████  ██  ██      ██  ██    ████
██        ████    ████  ████  ██████████    ██  ████      ████  ██  ████    ██
██  ██  ████  ██████  ████  ████    ██  ████    ██  ██  ██    ██████    ██████
██  ██    ██          ██  ████    ██  ██    ██        ████            ████████
██████████████████    ██    ████████    ████  ██████  ████  ██████        ████
██              ██  ██      ██        ██████████    ██████  ██  ██      ██  ██
██  ██████████  ██████  ████        ████████  ██        ██  ██████    ██  ████
██  ██      ██  ██    ████      ██    ██████████    ████            ████  ████
██  ██      ██  ██  ████    ████████  ██  ██  ████████      ██  ████  ████████
██  ██      ██  ████  ████████████    ████  ██  ██    ████  ████            ██
██  ██████████  ██████  ██████████████  ██  ██  ██████  ██████  ██  ██      ██
██              ████  ████    ████    ██  ██    ████  ████  ██  ████  ████  ██
██████████████████████████████████████████████████████████████████████████████
Please scan the QR code to log in.
Please press confirm on your phone.
Loading the contact, this may take a little while.
Traceback (most recent call last):
  File "robot.py", line 11, in <module>
    bot = Bot(cache_path=True, console_qr=True)
  File "/home/pi/.local/lib/python3.7/site-packages/wxpy/api/bot.py", line 86, in __init__
    loginCallback=login_callback, exitCallback=logout_callback
  File "/home/pi/.local/lib/python3.7/site-packages/itchat/components/register.py", line 30, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/home/pi/.local/lib/python3.7/site-packages/itchat/components/login.py", line 66, in login
    self.show_mobile_login()
  File "/home/pi/.local/lib/python3.7/site-packages/itchat/components/login.py", line 212, in show_mobile_login
    self.loginInfo['url'], self.loginInfo['pass_ticket'])
KeyError: 'pass_ticket'

**Comment by youzhouchang** [comment]
网页版微信不让登录，找到解决方案了吗

**Comment by Stripyuan** [comment]
没有 
------------------
The mail send to Strip.lue.

**Comment by Stripyuan** [comment]
没有 
------------------
The mail send to Strip.lue.

**Comment by pig6** [comment]
一般报：KeyError: 'pass_ticket' 基本都是网页版不能登录。

项目是基于微信网页版接口的，所以你要先试试是否可以登录网页版微信。

如果网页版不能登录那这个微信号就不能登录项目，需要更换微信。
