### ISSUE TITLE
登录报错

### ISSUE THREAD

**Issue by lunarjuhse** [pig6/wxrobot#15]
二维码可以正常扫描，在手机端确认信息后，报错信息如下：
`Traceback (most recent call last):
  File "C:/Users/chris/PycharmProjects/wxrobot/robot.py", line 11, in <module>
    bot = Bot(cache_path=True)
  File "C:\Users\chris\PycharmProjects\wechatrobot\venv\lib\site-packages\wxpy\api\bot.py", line 86, in __init__
    loginCallback=login_callback, exitCallback=logout_callback
  File "C:\Users\chris\PycharmProjects\wechatrobot\venv\lib\site-packages\itchat\components\register.py", line 30, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "C:\Users\chris\PycharmProjects\wechatrobot\venv\lib\site-packages\itchat\components\login.py", line 66, in login
    self.show_mobile_login()
  File "C:\Users\chris\PycharmProjects\wechatrobot\venv\lib\site-packages\itchat\components\login.py", line 212, in show_mobile_login
    self.loginInfo['url'], self.loginInfo['pass_ticket'])
KeyError: 'pass_ticket'

Process finished with exit code 1`

**Comment by tietou1xin** [comment]
网页版微信好像停用了，我的两个号都不能登录了，如果网页版你登不上去，这个就会报错。

**Comment by toooooop** [comment]
微信网页版做了限制，登录不了了，换号试试吧

**Comment by CZDGitH** [comment]
用不了了

**Comment by pig6** [comment]
一般报：KeyError: 'pass_ticket' 基本都是网页版不能登录。

项目是基于微信网页版接口的，所以你要先试试是否可以登录网页版微信。

如果网页版不能登录那这个微信号就不能登录项目，需要更换微信。

**Comment by wanghaozi** [comment]
很奇怪 我用我自己的号没问题,但是用新注册的号码就会报这个问题 而且试过 新注册的号码可以登陆网页版本, 求指教

**Comment by pig6** [comment]
新注册的号一般是不可以登录网页版微信

**Comment by ZhaoBuHui** [comment]
现在微信一般不能登入网页版微信怎么办

**Comment by songxinryc** [comment]
同样的问题



发自我的小米手机在 ZhaoBuHui <notifications@github.com>，2020年1月4日 上午11:58写道：现在微信一般不能登入网页版微信怎么办



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/pig6/wxrobot/issues/15?email_source=notifications\u0026email_token=ACWIVA5DHBVVXZXV5YM2H6LQ4ACNHA5CNFSM4IGBYLQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEICQJUA#issuecomment-570754256",

"url": "https://github.com/pig6/wxrobot/issues/15?email_source=notifications\u0026email_token=ACWIVA5DHBVVXZXV5YM2H6LQ4ACNHA5CNFSM4IGBYLQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEICQJUA#issuecomment-570754256",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by menh** [comment]
只能更换微信吗，这样岂不是很多都无法登陆。有从代码方面解决的方法吗

**Comment by ChristineHwuang** [comment]
这个感觉基本无法解决的了，微信的大方向就是封锁网页版登录。

Hu Men <notifications@github.com> 于2020年1月17日周五 上午10:59写道：

**Comment by vgtmci** [comment]
已经凉了, 网页版微信不让登陆了, 换了三个号都不行, 其中一个有七八年了的微信也不让登陆

**Comment by travellers** [comment]
微信是不能网页登陆了，然后./robot.py在扫码后直接退出了。

**Comment by travellers** [comment]
有什么好的替换方案吗？
